version: '3.9'
services:
  mongodb:
    container_name: mongo-dev
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME:"${MONGO_ROOT_USER}"
      - MONGO_INITDB_ROOT_PASSWORD:"${MONGO_ROOT_PASSWORD}"
      - MONGO_INITDB_DATABASE:"jupiter"
    ports:
      - '27017:27017'
  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54.0
    restart: always
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME="${MONGO_ROOT_USER}"
      - ME_CONFIG_MONGODB_ADMINPASSWORD="${MONGO_ROOT_PASSWORD}"
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    ports:
      - '8081:8081'
