version: '3.9'
services:
  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME:"${MONGO_INITDB_ROOT_USERNAME}"
      - MONGO_INITDB_ROOT_PASSWORD:"${MONGO_INITDB_ROOT_PASSWORD}"
  database_admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME="${ME_CONFIG_MONGODB_ADMINUSERNAME}"
      - ME_CONFIG_MONGODB_ADMINPASSWORD="${ME_CONFIG_MONGODB_ADMINPASSWORD}"
      - ME_CONFIG_MONGODB_URL="${ME_CONFIG_MONGODB_URL}"
